name: Lint

on:
  push:
    branches: [ "main", "feature/*", "fix/*" ]
  pull_request:
    branches: [ "main", "feature/*", "fix/*" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ESLint
        run: |
          npx eslint@8.x generate-constellation.js config.js \
          --no-eslintrc \
          --env browser \
          --env es6 \
          --rule '{"no-undef": "error", "no-unused-vars": "warn"}'

      - name: Lint HTML
        run: npx htmlhint "index.html"